### ISSUE TITLE
Determine if implicit solve reduces coarsening instability

### ISSUE THREAD

**Issue by kincaidkc** [kincaidkc/AdditiveFOAM#14]
The original intent of the persistence flag to prevent issues with the thermodynamic coupling when a cell coarsens. I think it is necessary to resolve the tail, but we should check if these numerical issues are solved by forcing an implicit solve whenever the mesh changes.

_Originally posted by @colemanjs in https://github.com/kincaidkc/AdditiveFOAM/pull/10#discussion_r1484684631_

**Comment by kincaidkc** [comment]
@colemanjs can we close this issue?

**Comment by colemanjs** [comment]
Yep!

**Comment by kincaidkc** [comment]
closed by #22
